// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: action_definitions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ActionTracer {

  /// <summary>Holder for reflection information generated from action_definitions.proto</summary>
  public static partial class ActionDefinitionsReflection {

    #region Descriptor
    /// <summary>File descriptor for action_definitions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActionDefinitionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhhY3Rpb25fZGVmaW5pdGlvbnMucHJvdG8SDEFjdGlvblRyYWNlciIxCg9B",
            "Y3Rpb25UaW1lc3RhbXASDwoHc2Vjb25kcxgBIAEoAxINCgVuYW5vcxgCIAEo",
            "BSLlBQoYQWN0aW9uRGF0YU5ldHdvcmtQYWNrYWdlEjAKCXNlbmRfdGltZRgB",
            "IAEoCzIdLkFjdGlvblRyYWNlci5BY3Rpb25UaW1lc3RhbXASFQoNcGFja2V0",
            "X251bWJlchgCIAEoDRJMCgtkZXZpY2VfZGF0YRgDIAMoCzI3LkFjdGlvblRy",
            "YWNlci5BY3Rpb25EYXRhTmV0d29ya1BhY2thZ2UuQWN0aW9uRGV2aWNlRGF0",
            "YRqxBAoQQWN0aW9uRGV2aWNlRGF0YRIiChpkZXZpY2VfaWRlbnRpZmllcl9j",
            "b250ZW50cxgEIAEoDRJXCgpxdWF0ZXJuaW9uGAUgASgLMkMuQWN0aW9uVHJh",
            "Y2VyLkFjdGlvbkRhdGFOZXR3b3JrUGFja2FnZS5BY3Rpb25EZXZpY2VEYXRh",
            "LkFjdGlvbkRhdGE0EloKDWFjY2VsZXJvbWV0ZXIYBiABKAsyQy5BY3Rpb25U",
            "cmFjZXIuQWN0aW9uRGF0YU5ldHdvcmtQYWNrYWdlLkFjdGlvbkRldmljZURh",
            "dGEuQWN0aW9uRGF0YTMSVgoJZ3lyb3Njb3BlGAcgASgLMkMuQWN0aW9uVHJh",
            "Y2VyLkFjdGlvbkRhdGFOZXR3b3JrUGFja2FnZS5BY3Rpb25EZXZpY2VEYXRh",
            "LkFjdGlvbkRhdGEzEhMKC3RlbXBlcmF0dXJlGAggASgCElIKBWV4dHJhGAkg",
            "AygLMkMuQWN0aW9uVHJhY2VyLkFjdGlvbkRhdGFOZXR3b3JrUGFja2FnZS5B",
            "Y3Rpb25EZXZpY2VEYXRhLkFjdGlvbkRhdGEzGhgKC0FjdGlvbkRhdGExEgkK",
            "AXgYASABKAIaLgoLQWN0aW9uRGF0YTMSCQoBeBgBIAEoAhIJCgF5GAIgASgC",
            "EgkKAXoYAyABKAIaOQoLQWN0aW9uRGF0YTQSCQoBdxgBIAEoAhIJCgF4GAIg",
            "ASgCEgkKAXkYAyABKAISCQoBehgEIAEoAiKNAgoNQWN0aW9uTWVzc2FnZRIr",
            "CgZhY3Rpb24YASABKA4yGy5BY3Rpb25UcmFjZXIuQWN0aW9uQ29tbWFuZBIM",
            "CgRuYW1lGAIgASgJEg0KBXBhcmFtGAMgASgFEjsKD2JvZHlfY29ubmVjdGlv",
            "bhgEIAEoDjIiLkFjdGlvblRyYWNlci5BY3Rpb25Cb2R5Q29ubmVjdGlvbhI/",
            "ChFkZXZpY2VfY29ubmVjdGlvbhgFIAEoDjIkLkFjdGlvblRyYWNlci5BY3Rp",
            "b25EZXZpY2VDb25uZWN0aW9uEjQKBGRhdGEYBiABKAsyJi5BY3Rpb25UcmFj",
            "ZXIuQWN0aW9uRGF0YU5ldHdvcmtQYWNrYWdlKoMBCg1BY3Rpb25Db21tYW5k",
            "EgsKB1VOS05PV04QABIJCgVTVEFSVBABEggKBFNUT1AQAhILCgdNQVBQSU5H",
            "EAMSDQoJVU5NQVBQSU5HEAQSDwoLT1VUUFVUX1JBVEUQBRIJCgVSRVNFVBAG",
            "EggKBERBVEEQBxIOCgpESVNDT05ORUNUEAgqlwIKFEFjdGlvbkJvZHlDb25u",
            "ZWN0aW9uEgkKBVdBSVNUEAASDwoLUklHSFRfQklDRVAQARIRCg1SSUdIVF9G",
            "T1JFQVJNEAISDgoKUklHSFRfSEFORBADEg4KCkxFRlRfQklDRVAQBBIQCgxM",
            "RUZUX0ZPUkVBUk0QBRINCglMRUZUX0hBTkQQBhIJCgVDSEVTVBAHEggKBEhF",
            "QUQQCBIPCgtSSUdIVF9USElHSBAJEg4KClJJR0hUX0tORUUQChIOCgpSSUdI",
            "VF9GT09UEAsSDgoKTEVGVF9USElHSBAMEg0KCUxFRlRfS05FRRANEg0KCUxF",
            "RlRfRk9PVBAOEg0KCVJJR0hUX0hJUBAPEgwKCExFRlRfSElQEBAqzgEKFkFj",
            "dGlvbkRldmljZUNvbm5lY3Rpb24SCQoFQUNUXzAQABIJCgVBQ1RfMRABEgkK",
            "BUFDVF8yEAISCQoFQUNUXzMQAxIJCgVBQ1RfNBAEEgkKBUFDVF81EAUSCQoF",
            "QUNUXzYQBhIJCgVBQ1RfNxAHEgkKBUFDVF84EAgSCQoFQUNUXzkQCRIKCgZB",
            "Q1RfMTAQChIKCgZBQ1RfMTEQCxIKCgZBQ1RfMTIQDBIKCgZBQ1RfMTMQDRIK",
            "CgZBQ1RfMTQQDhIKCgZBQ1RfMTUQD2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ActionTracer.ActionCommand), typeof(global::ActionTracer.ActionBodyConnection), typeof(global::ActionTracer.ActionDeviceConnection), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ActionTracer.ActionTimestamp), global::ActionTracer.ActionTimestamp.Parser, new[]{ "Seconds", "Nanos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ActionTracer.ActionDataNetworkPackage), global::ActionTracer.ActionDataNetworkPackage.Parser, new[]{ "SendTime", "PacketNumber", "DeviceData" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData), global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Parser, new[]{ "DeviceIdentifierContents", "Quaternion", "Accelerometer", "Gyroscope", "Temperature", "Extra" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData1), global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData1.Parser, new[]{ "X" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3), global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData4), global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData4.Parser, new[]{ "W", "X", "Y", "Z" }, null, null, null, null)})}),
            new pbr::GeneratedClrTypeInfo(typeof(global::ActionTracer.ActionMessage), global::ActionTracer.ActionMessage.Parser, new[]{ "Action", "Name", "Param", "BodyConnection", "DeviceConnection", "Data" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ActionCommand {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("START")] Start = 1,
    [pbr::OriginalName("STOP")] Stop = 2,
    [pbr::OriginalName("MAPPING")] Mapping = 3,
    [pbr::OriginalName("UNMAPPING")] Unmapping = 4,
    [pbr::OriginalName("OUTPUT_RATE")] OutputRate = 5,
    [pbr::OriginalName("RESET")] Reset = 6,
    [pbr::OriginalName("DATA")] Data = 7,
    [pbr::OriginalName("DISCONNECT")] Disconnect = 8,
  }

  public enum ActionBodyConnection {
    [pbr::OriginalName("WAIST")] Waist = 0,
    [pbr::OriginalName("RIGHT_BICEP")] RightBicep = 1,
    [pbr::OriginalName("RIGHT_FOREARM")] RightForearm = 2,
    [pbr::OriginalName("RIGHT_HAND")] RightHand = 3,
    [pbr::OriginalName("LEFT_BICEP")] LeftBicep = 4,
    [pbr::OriginalName("LEFT_FOREARM")] LeftForearm = 5,
    [pbr::OriginalName("LEFT_HAND")] LeftHand = 6,
    [pbr::OriginalName("CHEST")] Chest = 7,
    [pbr::OriginalName("HEAD")] Head = 8,
    [pbr::OriginalName("RIGHT_THIGH")] RightThigh = 9,
    [pbr::OriginalName("RIGHT_KNEE")] RightKnee = 10,
    [pbr::OriginalName("RIGHT_FOOT")] RightFoot = 11,
    [pbr::OriginalName("LEFT_THIGH")] LeftThigh = 12,
    [pbr::OriginalName("LEFT_KNEE")] LeftKnee = 13,
    [pbr::OriginalName("LEFT_FOOT")] LeftFoot = 14,
    [pbr::OriginalName("RIGHT_HIP")] RightHip = 15,
    [pbr::OriginalName("LEFT_HIP")] LeftHip = 16,
  }

  public enum ActionDeviceConnection {
    [pbr::OriginalName("ACT_0")] Act0 = 0,
    [pbr::OriginalName("ACT_1")] Act1 = 1,
    [pbr::OriginalName("ACT_2")] Act2 = 2,
    [pbr::OriginalName("ACT_3")] Act3 = 3,
    [pbr::OriginalName("ACT_4")] Act4 = 4,
    [pbr::OriginalName("ACT_5")] Act5 = 5,
    [pbr::OriginalName("ACT_6")] Act6 = 6,
    [pbr::OriginalName("ACT_7")] Act7 = 7,
    [pbr::OriginalName("ACT_8")] Act8 = 8,
    [pbr::OriginalName("ACT_9")] Act9 = 9,
    [pbr::OriginalName("ACT_10")] Act10 = 10,
    [pbr::OriginalName("ACT_11")] Act11 = 11,
    [pbr::OriginalName("ACT_12")] Act12 = 12,
    [pbr::OriginalName("ACT_13")] Act13 = 13,
    [pbr::OriginalName("ACT_14")] Act14 = 14,
    [pbr::OriginalName("ACT_15")] Act15 = 15,
  }

  #endregion

  #region Messages
  public sealed partial class ActionTimestamp : pb::IMessage<ActionTimestamp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionTimestamp> _parser = new pb::MessageParser<ActionTimestamp>(() => new ActionTimestamp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionTimestamp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ActionTracer.ActionDefinitionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionTimestamp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionTimestamp(ActionTimestamp other) : this() {
      seconds_ = other.seconds_;
      nanos_ = other.nanos_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionTimestamp Clone() {
      return new ActionTimestamp(this);
    }

    /// <summary>Field number for the "seconds" field.</summary>
    public const int SecondsFieldNumber = 1;
    private long seconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Seconds {
      get { return seconds_; }
      set {
        seconds_ = value;
      }
    }

    /// <summary>Field number for the "nanos" field.</summary>
    public const int NanosFieldNumber = 2;
    private int nanos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Nanos {
      get { return nanos_; }
      set {
        nanos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionTimestamp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionTimestamp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Seconds != other.Seconds) return false;
      if (Nanos != other.Nanos) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Seconds != 0L) hash ^= Seconds.GetHashCode();
      if (Nanos != 0) hash ^= Nanos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Seconds != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Seconds);
      }
      if (Nanos != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Nanos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Seconds != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Seconds);
      }
      if (Nanos != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Nanos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Seconds != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Seconds);
      }
      if (Nanos != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Nanos);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionTimestamp other) {
      if (other == null) {
        return;
      }
      if (other.Seconds != 0L) {
        Seconds = other.Seconds;
      }
      if (other.Nanos != 0) {
        Nanos = other.Nanos;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Seconds = input.ReadInt64();
            break;
          }
          case 16: {
            Nanos = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Seconds = input.ReadInt64();
            break;
          }
          case 16: {
            Nanos = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActionDataNetworkPackage : pb::IMessage<ActionDataNetworkPackage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionDataNetworkPackage> _parser = new pb::MessageParser<ActionDataNetworkPackage>(() => new ActionDataNetworkPackage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionDataNetworkPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ActionTracer.ActionDefinitionsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionDataNetworkPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionDataNetworkPackage(ActionDataNetworkPackage other) : this() {
      sendTime_ = other.sendTime_ != null ? other.sendTime_.Clone() : null;
      packetNumber_ = other.packetNumber_;
      deviceData_ = other.deviceData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionDataNetworkPackage Clone() {
      return new ActionDataNetworkPackage(this);
    }

    /// <summary>Field number for the "send_time" field.</summary>
    public const int SendTimeFieldNumber = 1;
    private global::ActionTracer.ActionTimestamp sendTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ActionTracer.ActionTimestamp SendTime {
      get { return sendTime_; }
      set {
        sendTime_ = value;
      }
    }

    /// <summary>Field number for the "packet_number" field.</summary>
    public const int PacketNumberFieldNumber = 2;
    private uint packetNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PacketNumber {
      get { return packetNumber_; }
      set {
        packetNumber_ = value;
      }
    }

    /// <summary>Field number for the "device_data" field.</summary>
    public const int DeviceDataFieldNumber = 3;
    private static readonly pb::FieldCodec<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData> _repeated_deviceData_codec
        = pb::FieldCodec.ForMessage(26, global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Parser);
    private readonly pbc::RepeatedField<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData> deviceData_ = new pbc::RepeatedField<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData> DeviceData {
      get { return deviceData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionDataNetworkPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionDataNetworkPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SendTime, other.SendTime)) return false;
      if (PacketNumber != other.PacketNumber) return false;
      if(!deviceData_.Equals(other.deviceData_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (sendTime_ != null) hash ^= SendTime.GetHashCode();
      if (PacketNumber != 0) hash ^= PacketNumber.GetHashCode();
      hash ^= deviceData_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (sendTime_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SendTime);
      }
      if (PacketNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(PacketNumber);
      }
      deviceData_.WriteTo(output, _repeated_deviceData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (sendTime_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SendTime);
      }
      if (PacketNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(PacketNumber);
      }
      deviceData_.WriteTo(ref output, _repeated_deviceData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (sendTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SendTime);
      }
      if (PacketNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PacketNumber);
      }
      size += deviceData_.CalculateSize(_repeated_deviceData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionDataNetworkPackage other) {
      if (other == null) {
        return;
      }
      if (other.sendTime_ != null) {
        if (sendTime_ == null) {
          SendTime = new global::ActionTracer.ActionTimestamp();
        }
        SendTime.MergeFrom(other.SendTime);
      }
      if (other.PacketNumber != 0) {
        PacketNumber = other.PacketNumber;
      }
      deviceData_.Add(other.deviceData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (sendTime_ == null) {
              SendTime = new global::ActionTracer.ActionTimestamp();
            }
            input.ReadMessage(SendTime);
            break;
          }
          case 16: {
            PacketNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            deviceData_.AddEntriesFrom(input, _repeated_deviceData_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (sendTime_ == null) {
              SendTime = new global::ActionTracer.ActionTimestamp();
            }
            input.ReadMessage(SendTime);
            break;
          }
          case 16: {
            PacketNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            deviceData_.AddEntriesFrom(ref input, _repeated_deviceData_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ActionDataNetworkPackage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class ActionDeviceData : pb::IMessage<ActionDeviceData>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ActionDeviceData> _parser = new pb::MessageParser<ActionDeviceData>(() => new ActionDeviceData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ActionDeviceData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ActionTracer.ActionDataNetworkPackage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ActionDeviceData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ActionDeviceData(ActionDeviceData other) : this() {
          deviceIdentifierContents_ = other.deviceIdentifierContents_;
          quaternion_ = other.quaternion_ != null ? other.quaternion_.Clone() : null;
          accelerometer_ = other.accelerometer_ != null ? other.accelerometer_.Clone() : null;
          gyroscope_ = other.gyroscope_ != null ? other.gyroscope_.Clone() : null;
          temperature_ = other.temperature_;
          extra_ = other.extra_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ActionDeviceData Clone() {
          return new ActionDeviceData(this);
        }

        /// <summary>Field number for the "device_identifier_contents" field.</summary>
        public const int DeviceIdentifierContentsFieldNumber = 4;
        private uint deviceIdentifierContents_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint DeviceIdentifierContents {
          get { return deviceIdentifierContents_; }
          set {
            deviceIdentifierContents_ = value;
          }
        }

        /// <summary>Field number for the "quaternion" field.</summary>
        public const int QuaternionFieldNumber = 5;
        private global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData4 quaternion_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData4 Quaternion {
          get { return quaternion_; }
          set {
            quaternion_ = value;
          }
        }

        /// <summary>Field number for the "accelerometer" field.</summary>
        public const int AccelerometerFieldNumber = 6;
        private global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3 accelerometer_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3 Accelerometer {
          get { return accelerometer_; }
          set {
            accelerometer_ = value;
          }
        }

        /// <summary>Field number for the "gyroscope" field.</summary>
        public const int GyroscopeFieldNumber = 7;
        private global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3 gyroscope_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3 Gyroscope {
          get { return gyroscope_; }
          set {
            gyroscope_ = value;
          }
        }

        /// <summary>Field number for the "temperature" field.</summary>
        public const int TemperatureFieldNumber = 8;
        private float temperature_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Temperature {
          get { return temperature_; }
          set {
            temperature_ = value;
          }
        }

        /// <summary>Field number for the "extra" field.</summary>
        public const int ExtraFieldNumber = 9;
        private static readonly pb::FieldCodec<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3> _repeated_extra_codec
            = pb::FieldCodec.ForMessage(74, global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3.Parser);
        private readonly pbc::RepeatedField<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3> extra_ = new pbc::RepeatedField<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3> Extra {
          get { return extra_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ActionDeviceData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ActionDeviceData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (DeviceIdentifierContents != other.DeviceIdentifierContents) return false;
          if (!object.Equals(Quaternion, other.Quaternion)) return false;
          if (!object.Equals(Accelerometer, other.Accelerometer)) return false;
          if (!object.Equals(Gyroscope, other.Gyroscope)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Temperature, other.Temperature)) return false;
          if(!extra_.Equals(other.extra_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (DeviceIdentifierContents != 0) hash ^= DeviceIdentifierContents.GetHashCode();
          if (quaternion_ != null) hash ^= Quaternion.GetHashCode();
          if (accelerometer_ != null) hash ^= Accelerometer.GetHashCode();
          if (gyroscope_ != null) hash ^= Gyroscope.GetHashCode();
          if (Temperature != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Temperature);
          hash ^= extra_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (DeviceIdentifierContents != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(DeviceIdentifierContents);
          }
          if (quaternion_ != null) {
            output.WriteRawTag(42);
            output.WriteMessage(Quaternion);
          }
          if (accelerometer_ != null) {
            output.WriteRawTag(50);
            output.WriteMessage(Accelerometer);
          }
          if (gyroscope_ != null) {
            output.WriteRawTag(58);
            output.WriteMessage(Gyroscope);
          }
          if (Temperature != 0F) {
            output.WriteRawTag(69);
            output.WriteFloat(Temperature);
          }
          extra_.WriteTo(output, _repeated_extra_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (DeviceIdentifierContents != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(DeviceIdentifierContents);
          }
          if (quaternion_ != null) {
            output.WriteRawTag(42);
            output.WriteMessage(Quaternion);
          }
          if (accelerometer_ != null) {
            output.WriteRawTag(50);
            output.WriteMessage(Accelerometer);
          }
          if (gyroscope_ != null) {
            output.WriteRawTag(58);
            output.WriteMessage(Gyroscope);
          }
          if (Temperature != 0F) {
            output.WriteRawTag(69);
            output.WriteFloat(Temperature);
          }
          extra_.WriteTo(ref output, _repeated_extra_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (DeviceIdentifierContents != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DeviceIdentifierContents);
          }
          if (quaternion_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Quaternion);
          }
          if (accelerometer_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Accelerometer);
          }
          if (gyroscope_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gyroscope);
          }
          if (Temperature != 0F) {
            size += 1 + 4;
          }
          size += extra_.CalculateSize(_repeated_extra_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ActionDeviceData other) {
          if (other == null) {
            return;
          }
          if (other.DeviceIdentifierContents != 0) {
            DeviceIdentifierContents = other.DeviceIdentifierContents;
          }
          if (other.quaternion_ != null) {
            if (quaternion_ == null) {
              Quaternion = new global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData4();
            }
            Quaternion.MergeFrom(other.Quaternion);
          }
          if (other.accelerometer_ != null) {
            if (accelerometer_ == null) {
              Accelerometer = new global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3();
            }
            Accelerometer.MergeFrom(other.Accelerometer);
          }
          if (other.gyroscope_ != null) {
            if (gyroscope_ == null) {
              Gyroscope = new global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3();
            }
            Gyroscope.MergeFrom(other.Gyroscope);
          }
          if (other.Temperature != 0F) {
            Temperature = other.Temperature;
          }
          extra_.Add(other.extra_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 32: {
                DeviceIdentifierContents = input.ReadUInt32();
                break;
              }
              case 42: {
                if (quaternion_ == null) {
                  Quaternion = new global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData4();
                }
                input.ReadMessage(Quaternion);
                break;
              }
              case 50: {
                if (accelerometer_ == null) {
                  Accelerometer = new global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3();
                }
                input.ReadMessage(Accelerometer);
                break;
              }
              case 58: {
                if (gyroscope_ == null) {
                  Gyroscope = new global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3();
                }
                input.ReadMessage(Gyroscope);
                break;
              }
              case 69: {
                Temperature = input.ReadFloat();
                break;
              }
              case 74: {
                extra_.AddEntriesFrom(input, _repeated_extra_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 32: {
                DeviceIdentifierContents = input.ReadUInt32();
                break;
              }
              case 42: {
                if (quaternion_ == null) {
                  Quaternion = new global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData4();
                }
                input.ReadMessage(Quaternion);
                break;
              }
              case 50: {
                if (accelerometer_ == null) {
                  Accelerometer = new global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3();
                }
                input.ReadMessage(Accelerometer);
                break;
              }
              case 58: {
                if (gyroscope_ == null) {
                  Gyroscope = new global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Types.ActionData3();
                }
                input.ReadMessage(Gyroscope);
                break;
              }
              case 69: {
                Temperature = input.ReadFloat();
                break;
              }
              case 74: {
                extra_.AddEntriesFrom(ref input, _repeated_extra_codec);
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the ActionDeviceData message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public sealed partial class ActionData1 : pb::IMessage<ActionData1>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<ActionData1> _parser = new pb::MessageParser<ActionData1>(() => new ActionData1());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<ActionData1> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ActionData1() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ActionData1(ActionData1 other) : this() {
              x_ = other.x_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ActionData1 Clone() {
              return new ActionData1(this);
            }

            /// <summary>Field number for the "x" field.</summary>
            public const int XFieldNumber = 1;
            private float x_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public float X {
              get { return x_; }
              set {
                x_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as ActionData1);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(ActionData1 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (X != 0F) {
                output.WriteRawTag(13);
                output.WriteFloat(X);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (X != 0F) {
                output.WriteRawTag(13);
                output.WriteFloat(X);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (X != 0F) {
                size += 1 + 4;
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(ActionData1 other) {
              if (other == null) {
                return;
              }
              if (other.X != 0F) {
                X = other.X;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 13: {
                    X = input.ReadFloat();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 13: {
                    X = input.ReadFloat();
                    break;
                  }
                }
              }
            }
            #endif

          }

          public sealed partial class ActionData3 : pb::IMessage<ActionData3>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<ActionData3> _parser = new pb::MessageParser<ActionData3>(() => new ActionData3());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<ActionData3> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Descriptor.NestedTypes[1]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ActionData3() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ActionData3(ActionData3 other) : this() {
              x_ = other.x_;
              y_ = other.y_;
              z_ = other.z_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ActionData3 Clone() {
              return new ActionData3(this);
            }

            /// <summary>Field number for the "x" field.</summary>
            public const int XFieldNumber = 1;
            private float x_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public float X {
              get { return x_; }
              set {
                x_ = value;
              }
            }

            /// <summary>Field number for the "y" field.</summary>
            public const int YFieldNumber = 2;
            private float y_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public float Y {
              get { return y_; }
              set {
                y_ = value;
              }
            }

            /// <summary>Field number for the "z" field.</summary>
            public const int ZFieldNumber = 3;
            private float z_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public float Z {
              get { return z_; }
              set {
                z_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as ActionData3);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(ActionData3 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
              if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
              if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (X != 0F) {
                output.WriteRawTag(13);
                output.WriteFloat(X);
              }
              if (Y != 0F) {
                output.WriteRawTag(21);
                output.WriteFloat(Y);
              }
              if (Z != 0F) {
                output.WriteRawTag(29);
                output.WriteFloat(Z);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (X != 0F) {
                output.WriteRawTag(13);
                output.WriteFloat(X);
              }
              if (Y != 0F) {
                output.WriteRawTag(21);
                output.WriteFloat(Y);
              }
              if (Z != 0F) {
                output.WriteRawTag(29);
                output.WriteFloat(Z);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (X != 0F) {
                size += 1 + 4;
              }
              if (Y != 0F) {
                size += 1 + 4;
              }
              if (Z != 0F) {
                size += 1 + 4;
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(ActionData3 other) {
              if (other == null) {
                return;
              }
              if (other.X != 0F) {
                X = other.X;
              }
              if (other.Y != 0F) {
                Y = other.Y;
              }
              if (other.Z != 0F) {
                Z = other.Z;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 13: {
                    X = input.ReadFloat();
                    break;
                  }
                  case 21: {
                    Y = input.ReadFloat();
                    break;
                  }
                  case 29: {
                    Z = input.ReadFloat();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 13: {
                    X = input.ReadFloat();
                    break;
                  }
                  case 21: {
                    Y = input.ReadFloat();
                    break;
                  }
                  case 29: {
                    Z = input.ReadFloat();
                    break;
                  }
                }
              }
            }
            #endif

          }

          public sealed partial class ActionData4 : pb::IMessage<ActionData4>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<ActionData4> _parser = new pb::MessageParser<ActionData4>(() => new ActionData4());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<ActionData4> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Descriptor.NestedTypes[2]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ActionData4() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ActionData4(ActionData4 other) : this() {
              w_ = other.w_;
              x_ = other.x_;
              y_ = other.y_;
              z_ = other.z_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ActionData4 Clone() {
              return new ActionData4(this);
            }

            /// <summary>Field number for the "w" field.</summary>
            public const int WFieldNumber = 1;
            private float w_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public float W {
              get { return w_; }
              set {
                w_ = value;
              }
            }

            /// <summary>Field number for the "x" field.</summary>
            public const int XFieldNumber = 2;
            private float x_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public float X {
              get { return x_; }
              set {
                x_ = value;
              }
            }

            /// <summary>Field number for the "y" field.</summary>
            public const int YFieldNumber = 3;
            private float y_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public float Y {
              get { return y_; }
              set {
                y_ = value;
              }
            }

            /// <summary>Field number for the "z" field.</summary>
            public const int ZFieldNumber = 4;
            private float z_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public float Z {
              get { return z_; }
              set {
                z_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as ActionData4);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(ActionData4 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(W, other.W)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (W != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(W);
              if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
              if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
              if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (W != 0F) {
                output.WriteRawTag(13);
                output.WriteFloat(W);
              }
              if (X != 0F) {
                output.WriteRawTag(21);
                output.WriteFloat(X);
              }
              if (Y != 0F) {
                output.WriteRawTag(29);
                output.WriteFloat(Y);
              }
              if (Z != 0F) {
                output.WriteRawTag(37);
                output.WriteFloat(Z);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (W != 0F) {
                output.WriteRawTag(13);
                output.WriteFloat(W);
              }
              if (X != 0F) {
                output.WriteRawTag(21);
                output.WriteFloat(X);
              }
              if (Y != 0F) {
                output.WriteRawTag(29);
                output.WriteFloat(Y);
              }
              if (Z != 0F) {
                output.WriteRawTag(37);
                output.WriteFloat(Z);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (W != 0F) {
                size += 1 + 4;
              }
              if (X != 0F) {
                size += 1 + 4;
              }
              if (Y != 0F) {
                size += 1 + 4;
              }
              if (Z != 0F) {
                size += 1 + 4;
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(ActionData4 other) {
              if (other == null) {
                return;
              }
              if (other.W != 0F) {
                W = other.W;
              }
              if (other.X != 0F) {
                X = other.X;
              }
              if (other.Y != 0F) {
                Y = other.Y;
              }
              if (other.Z != 0F) {
                Z = other.Z;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 13: {
                    W = input.ReadFloat();
                    break;
                  }
                  case 21: {
                    X = input.ReadFloat();
                    break;
                  }
                  case 29: {
                    Y = input.ReadFloat();
                    break;
                  }
                  case 37: {
                    Z = input.ReadFloat();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 13: {
                    W = input.ReadFloat();
                    break;
                  }
                  case 21: {
                    X = input.ReadFloat();
                    break;
                  }
                  case 29: {
                    Y = input.ReadFloat();
                    break;
                  }
                  case 37: {
                    Z = input.ReadFloat();
                    break;
                  }
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

    }
    #endregion

  }

  public sealed partial class ActionMessage : pb::IMessage<ActionMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionMessage> _parser = new pb::MessageParser<ActionMessage>(() => new ActionMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ActionTracer.ActionDefinitionsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionMessage(ActionMessage other) : this() {
      action_ = other.action_;
      name_ = other.name_;
      param_ = other.param_;
      bodyConnection_ = other.bodyConnection_;
      deviceConnection_ = other.deviceConnection_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionMessage Clone() {
      return new ActionMessage(this);
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 1;
    private global::ActionTracer.ActionCommand action_ = global::ActionTracer.ActionCommand.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ActionTracer.ActionCommand Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "param" field.</summary>
    public const int ParamFieldNumber = 3;
    private int param_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Param {
      get { return param_; }
      set {
        param_ = value;
      }
    }

    /// <summary>Field number for the "body_connection" field.</summary>
    public const int BodyConnectionFieldNumber = 4;
    private global::ActionTracer.ActionBodyConnection bodyConnection_ = global::ActionTracer.ActionBodyConnection.Waist;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ActionTracer.ActionBodyConnection BodyConnection {
      get { return bodyConnection_; }
      set {
        bodyConnection_ = value;
      }
    }

    /// <summary>Field number for the "device_connection" field.</summary>
    public const int DeviceConnectionFieldNumber = 5;
    private global::ActionTracer.ActionDeviceConnection deviceConnection_ = global::ActionTracer.ActionDeviceConnection.Act0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ActionTracer.ActionDeviceConnection DeviceConnection {
      get { return deviceConnection_; }
      set {
        deviceConnection_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 6;
    private global::ActionTracer.ActionDataNetworkPackage data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ActionTracer.ActionDataNetworkPackage Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Action != other.Action) return false;
      if (Name != other.Name) return false;
      if (Param != other.Param) return false;
      if (BodyConnection != other.BodyConnection) return false;
      if (DeviceConnection != other.DeviceConnection) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Action != global::ActionTracer.ActionCommand.Unknown) hash ^= Action.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Param != 0) hash ^= Param.GetHashCode();
      if (BodyConnection != global::ActionTracer.ActionBodyConnection.Waist) hash ^= BodyConnection.GetHashCode();
      if (DeviceConnection != global::ActionTracer.ActionDeviceConnection.Act0) hash ^= DeviceConnection.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Action != global::ActionTracer.ActionCommand.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Param != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Param);
      }
      if (BodyConnection != global::ActionTracer.ActionBodyConnection.Waist) {
        output.WriteRawTag(32);
        output.WriteEnum((int) BodyConnection);
      }
      if (DeviceConnection != global::ActionTracer.ActionDeviceConnection.Act0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) DeviceConnection);
      }
      if (data_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Action != global::ActionTracer.ActionCommand.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Param != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Param);
      }
      if (BodyConnection != global::ActionTracer.ActionBodyConnection.Waist) {
        output.WriteRawTag(32);
        output.WriteEnum((int) BodyConnection);
      }
      if (DeviceConnection != global::ActionTracer.ActionDeviceConnection.Act0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) DeviceConnection);
      }
      if (data_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Action != global::ActionTracer.ActionCommand.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Action);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Param != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Param);
      }
      if (BodyConnection != global::ActionTracer.ActionBodyConnection.Waist) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BodyConnection);
      }
      if (DeviceConnection != global::ActionTracer.ActionDeviceConnection.Act0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DeviceConnection);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionMessage other) {
      if (other == null) {
        return;
      }
      if (other.Action != global::ActionTracer.ActionCommand.Unknown) {
        Action = other.Action;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Param != 0) {
        Param = other.Param;
      }
      if (other.BodyConnection != global::ActionTracer.ActionBodyConnection.Waist) {
        BodyConnection = other.BodyConnection;
      }
      if (other.DeviceConnection != global::ActionTracer.ActionDeviceConnection.Act0) {
        DeviceConnection = other.DeviceConnection;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::ActionTracer.ActionDataNetworkPackage();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Action = (global::ActionTracer.ActionCommand) input.ReadEnum();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Param = input.ReadInt32();
            break;
          }
          case 32: {
            BodyConnection = (global::ActionTracer.ActionBodyConnection) input.ReadEnum();
            break;
          }
          case 40: {
            DeviceConnection = (global::ActionTracer.ActionDeviceConnection) input.ReadEnum();
            break;
          }
          case 50: {
            if (data_ == null) {
              Data = new global::ActionTracer.ActionDataNetworkPackage();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Action = (global::ActionTracer.ActionCommand) input.ReadEnum();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Param = input.ReadInt32();
            break;
          }
          case 32: {
            BodyConnection = (global::ActionTracer.ActionBodyConnection) input.ReadEnum();
            break;
          }
          case 40: {
            DeviceConnection = (global::ActionTracer.ActionDeviceConnection) input.ReadEnum();
            break;
          }
          case 50: {
            if (data_ == null) {
              Data = new global::ActionTracer.ActionDataNetworkPackage();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
